### PR TITLE
Enable non-wave files even without pydub by calling ffmpeg directly

### PR DESCRIPTION
**Pull request by alyssarosenzweig**

### CODE REVIEW

**Comment by bobbybee** [comment]
This closes #8

**Comment by steveway** [comment]
Hello bobbybee,
Thank you for both of your Pull-Requests.
They do look good, haven't tested this yet but it'll likely work as far as I can see.
I hadn't been working on my QT Port in quite a few weeks now, because of work and other projects, but luckily this should not affect that.
I'll try to continue soon with the port, for anyone interested.
We'll likely merge your changes after a "quick" test, that could take some time depending on when someone has the time to do that.

**Comment by bobbybee** [comment]
Alright, thanks :)

**Comment by morevnaproject** [comment]
Hmmm.. With this fix we can get rid of pydub completely (since we can call ffmpeg directly), am I right?

**Comment by bobbybee** [comment]
Yes. I added an additional commit that removes pydub completely;
everything still seems to work as expected.

**Pull request closed without merging**
