### PR TITLE
Added CMU 39 phoneme set created by Hunanbean.

### PR DESCRIPTION
**Pull request by steveway**
Origin is this Repo from @Hunanbean [Papagayo-NG-Additions](https://github.com/Hunanbean-Collective/Papagayo-NG-Additions)

### CODE REVIEW

**Comment by morevnaproject** [comment]
Do we also need json file? ^__^

**Comment by steveway** [comment]
Whoops, I believe I didn't have all the files marked in my commit before. 
Now it should include everything.

**Comment by Hunanbean** [comment]
Very cool, hopefully everything goes smoothly

Thanks a bunch!

also, a video of the beta 0.4 version [https://www.youtube.com/watch?v=Y6pfMW6QyIE](url) it contains quite a few improvements, and is a better demonstration.

**Comment by morevnaproject** [comment]
Cool!

**Comment by Hunanbean** [comment]
Hello, i was wondering if you are waiting for a further update on my end, or if something went wrong with the merge.
Please let me know. Thanks

**Comment by steveway** [comment]
Hi,
Nope I just didn't find the time to do that yet.
Everything seems to be ok, so I'll merge this.

**Comment by Hunanbean** [comment]
Cool deal, Thanks a bunch!
there has been some traffic on my git, so hopefully this can add some users
to Papagayo-NG from the MakeHuman users. I incorporated the visemes into
the mhx2 importer, so now for end users it is basically just a checkbox on
import and they are up and running.

**Pull request merged**
